### ISSUE TITLE
IDF version

### ISSUE THREAD

**Issue by michael-betz** [Spritetm/minimacplus#4]
Hi Spritetm,

do you happen to remember which version of esp-idf you were using?

I've managed to get it to compile with `esp-idf-v3.0.8.zip` after some minor tweaks to the code. However the display stays dark and it looks like my MIPI waveforms are slightly messed up. 

I think what would be helpful at this point are some known-good binarys (either to download or compile myself) to exclude any issues on the software side.

Many greetings,
Michael

**Comment by michael-betz** [comment]
All good, display works. 

Turns out I had a cold solder joint at the connector. 
Idf v3.0.8 seems to be a good choice to get the code running with relatively little modifications.

I'll be having a look if I can use the display with IDF6 and the new SPI driver.

Many thanks for sharing this cool project!

**Comment by Spritetm** [comment]
Glad you got it resolved! Yeah, those connectors are tricky to get soldered just right.
